version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DatabaseProvider=MariaDB
      - 'ConnectionStrings:MariaDBConnection=server=db;port=3306;database=graduation;user=user;password=supersecret'
    links:
      - db
  db:
    image: "mariadb"
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=devP@$$!
      - MYSQL_USER=user
      - MYSQL_PASSWORD=supersecret
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=supersecret
      #- PMA_ARBITRARY=1
    links:
      - db